#!/usr/bin/env python3
"""Bake the hand-synced copies of the site's page list from site.json (WS-10).

  python3 tools/bake.py [--check] [--only TARGET ...] [--root PATH]

Rewrites only marked regions and generated files. Targets, in run order:
  header-fallback  assets/site.js         /* bake:header-fallback */ ... /* /bake */  (one-line JS string)
  palette-items    assets/site.js         /* bake:palette-items */ ... /* /bake */    (lines of var ITEMS)
  noscript         pages                  <!-- bake:noscript --> ... <!-- /bake -->
  header-nav       partials/header.html   <!-- bake:header-nav --> ... <!-- /bake -->  (skipped until marked)
  sitemap          sitemap.xml            whole file; lastmod from git
  stubs            the redirect pages in site.json "stubs": whole files from tools/templates/
--check bakes in memory, prints "DRIFT <path> <target>" per difference and exits 1; a sitemap
lastmod difference alone is not drift (a shallow CI clone cannot know it).
Strings in site.json are source text for HTML or JS and are inserted as written.
Standard library only; Python 3.9 and later.
"""
from __future__ import annotations

import argparse
import datetime
import fnmatch
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SITE_ORIGIN = "https://gilly.space"
DOT = "·"
HEADER_TEMPLATE = (
    '<a class="skip-link" href="#main">Skip to content</a><header class="site-header">'
    '<div class="site-header__inner"><a class="brand" href="/">gilly<span class="dot">.</span>space</a>'
    '<nav class="site-nav" aria-label="Primary">{links}</nav></div></header>'
)
SITEMAP_HEAD = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- Generated by tools/bake.py from site.json. Edit site.json, then run python3 tools/bake.py. -->\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
)
LASTMOD_RE = re.compile(r"<lastmod>[^<]*</lastmod>")


class BakeError(Exception):
    pass


def read_file(path: pathlib.Path) -> str:
    with open(path, encoding="utf-8", newline="") as fh:
        return fh.read()


def write_file(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)


class Ctx:
    """Files are read through an overlay, so a target sees the output of the targets before it."""

    def __init__(self, root, site, today=None):
        self.root = pathlib.Path(root)
        self.site = site
        self.today = today or datetime.date.today()
        self.out = {}

    def exists(self, rel: str) -> bool:
        return (self.root / rel).is_file()

    def disk(self, rel: str) -> str:
        try:
            return read_file(self.root / rel)
        except OSError as e:
            raise BakeError(f"cannot read {rel}: {e.strerror or e}")

    def read(self, rel: str) -> str:
        return self.out[rel] if rel in self.out else self.disk(rel)


def load_site(root: pathlib.Path) -> dict:
    p = root / "site.json"
    try:
        site = json.loads(read_file(p))
    except (OSError, ValueError) as e:
        raise BakeError(f"site.json: {e}")
    if site.get("schema") != 1:
        raise BakeError("site.json: schema must be 1")
    for key in ("nav", "pages", "palette_extra", "stubs"):
        if key not in site:
            raise BakeError(f"site.json: missing key {key!r}")
    for page in site["pages"]:
        if not (root / page["path"]).is_file():
            raise BakeError(f"site.json: no file {page['path']}")
    return site


def replace_region(text: str, name: str, body: str, style: str) -> str:
    """Replace what lies between the markers for `name`; exactly one region or BakeError.

    "html":      <!-- bake:NAME --> ... <!-- /bake -->, body on its own lines
    "js":        /* bake:NAME */ ... /* /bake */, body on its own lines
    "js-inline": the same JS markers, body between single spaces
    The closing marker keeps the indentation it has.
    """
    if style == "html":
        open_, close = f"<!-- bake:{name} -->", "<!-- /bake -->"
    elif style in ("js", "js-inline"):
        open_, close = f"/* bake:{name} */", "/* /bake */"
    else:
        raise BakeError(f"unknown style {style!r}")
    n = text.count(open_)
    if n != 1:
        raise BakeError(f"expected exactly 1 {open_!r}, found {n}")
    i = text.index(open_) + len(open_)
    j = text.find(close, i)
    if j < 0:
        raise BakeError(f"{open_!r} has no {close!r} after it")
    if style == "js-inline":
        mid = " " + body + " "
    else:
        indent = re.search(r"[ \t]*\Z", text[i:j]).group(0)
        mid = "\n" + body + "\n" + indent
    return text[:i] + mid + text[j:]


def js_quote(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_header_fallback(site: dict) -> str:
    links = " ".join(f'<a href="{n["href"]}">{n["label"]}</a>' for n in site["nav"])
    return js_quote(HEADER_TEMPLATE.format(links=links))


def render_palette_items(site: dict) -> str:
    rows = [(p["palette"], p["url"], p["keywords"]) for p in site["pages"] if p.get("palette")]
    rows += [(e["t"], e["u"], e["k"]) for e in site["palette_extra"]]
    return ",\n".join(f"      {{ t: {js_quote(t)}, u: {js_quote(u)}, k: {js_quote(k)} }}" for t, u, k in rows)


def render_noscript(site: dict, mode: str = "nav") -> str:
    if mode == "home":
        return '<noscript><nav class="wrap" style="padding-top:12px"><a href="/">Home</a></nav></noscript>'
    if mode != "nav":
        raise BakeError(f"unknown noscript mode {mode!r}")
    links = f" {DOT}\n".join(f'    <a href="{n["href"]}">{n["label"]}</a>' for n in site["nav"])
    return '<noscript>\n  <nav class="wrap" style="padding-top:12px" aria-label="Primary">\n' + links + "\n  </nav>\n</noscript>"


def render_header_nav(site: dict) -> str:
    out = []
    for n in site["nav"]:
        kids = n.get("children")
        if not kids:
            out.append(f'      <a href="{n["href"]}">{n["label"]}</a>')
            continue
        out.append('      <div class="nav-drop">')
        out.append(f'        <a href="{n["href"]}">{n["label"]}<span class="nav-drop__caret" aria-hidden="true"></span></a>')
        out.append('        <div class="nav-drop__menu">')
        for c in kids:
            if c.get("icon"):
                art = f'<img class="sw-icon" src="{c["icon"]}" alt="">'
            else:
                art = f'<span class="sw-mark sw-mark--{c["mark"]}" aria-hidden="true"></span>'
            out.append(f'          <a href="{c["href"]}">{art}<span><b>{c["label"]}</b><small>{c["blurb"]}</small></span></a>')
        out.append("        </div>")
        out.append("      </div>")
    return "\n".join(out)


def archived_globs(root: pathlib.Path) -> list:
    p = root / "tools" / "archived_pages.txt"
    if not p.is_file():
        return []
    lines = (ln.split("#", 1)[0].strip() for ln in read_file(p).splitlines())
    return [ln for ln in lines if ln]


def lastmod(ctx: Ctx, rel: str) -> str:
    r = subprocess.run(["git", "-C", str(ctx.root), "log", "-1", "--format=%cs", "--", rel],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 and r.stdout.strip() else ctx.today.isoformat()


def render_sitemap(ctx: Ctx) -> str:
    skip = archived_globs(ctx.root)
    rows = []
    for p in ctx.site["pages"]:
        if not p.get("sitemap") or p.get("archived") or any(fnmatch.fnmatchcase(p["path"], g) for g in skip):
            continue
        rows.append(f'  <url><loc>{SITE_ORIGIN}{p["url"]}</loc><priority>{p["priority"]}</priority>'
                    f'<lastmod>{lastmod(ctx, p["path"])}</lastmod></url>')
    return SITEMAP_HEAD + "\n".join(rows) + "\n</urlset>\n"


def render_stub(ctx: Ctx, stub: dict) -> str:
    tpl = ctx.disk("tools/templates/" + stub["template"])
    return (tpl.replace("__TITLE__", stub["title"])
               .replace("__CANONICAL__", stub.get("canonical", stub["target"]))
               .replace("__TARGET__", stub["target"]))


def t_header_fallback(ctx: Ctx) -> dict:
    rel = "assets/site.js"
    return {rel: replace_region(ctx.read(rel), "header-fallback", render_header_fallback(ctx.site), "js-inline")}


def t_palette_items(ctx: Ctx) -> dict:
    rel = "assets/site.js"
    return {rel: replace_region(ctx.read(rel), "palette-items", render_palette_items(ctx.site), "js")}


def t_noscript(ctx: Ctx) -> dict:
    out = {}
    for p in ctx.site["pages"]:
        text = ctx.read(p["path"])
        if "<!-- bake:noscript -->" in text:
            out[p["path"]] = replace_region(text, "noscript", render_noscript(ctx.site, p.get("noscript", "nav")), "html")
    return out


def t_header_nav(ctx: Ctx) -> dict:
    rel = "partials/header.html"
    if not ctx.exists(rel) or "<!-- bake:header-nav -->" not in ctx.read(rel):
        return {}
    return {rel: replace_region(ctx.read(rel), "header-nav", render_header_nav(ctx.site), "html")}


def t_sitemap(ctx: Ctx) -> dict:
    return {"sitemap.xml": render_sitemap(ctx)}


def t_stubs(ctx: Ctx) -> dict:
    return {s["path"]: render_stub(ctx, s) for s in ctx.site["stubs"]}


TARGETS = {
    "header-fallback": t_header_fallback,
    "palette-items": t_palette_items,
    "noscript": t_noscript,
    "header-nav": t_header_nav,
    "sitemap": t_sitemap,
    "stubs": t_stubs,
}


def differs(name: str, old: str, new: str) -> bool:
    if name == "sitemap":
        old, new = LASTMOD_RE.sub("<lastmod/>", old), LASTMOD_RE.sub("<lastmod/>", new)
    return old != new


def run(ctx: Ctx, names=None) -> list:
    """Run the targets in order; return [(path, target)] for every file whose text would change."""
    drift = []
    for name, fn in TARGETS.items():
        if names and name not in names:
            continue
        for rel, new in fn(ctx).items():
            if not ctx.exists(rel) or differs(name, ctx.read(rel), new):
                drift.append((rel, name))
            ctx.out[rel] = new
    return drift


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Bake site.json into the hand-synced copies.")
    ap.add_argument("--check", action="store_true", help="change nothing; exit 1 on drift")
    ap.add_argument("--only", nargs="+", action="extend", metavar="TARGET", choices=list(TARGETS))
    ap.add_argument("--root", type=pathlib.Path, default=ROOT)
    a = ap.parse_args(argv)
    root = a.root.resolve()
    try:
        ctx = Ctx(root, load_site(root))
        drift = run(ctx, a.only)
    except BakeError as e:
        print(f"ERROR bake: {e}")
        return 1
    if a.check:
        for rel, name in drift:
            print(f"DRIFT {rel} {name}")
        return 1 if drift else 0
    written = 0
    for rel, text in ctx.out.items():
        if not ctx.exists(rel) or ctx.disk(rel) != text:
            write_file(root / rel, text)
            print(f"baked {rel}")
            written += 1
    print(f"bake: {written} file(s) written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
