#!/usr/bin/env python3
"""Build assets/icons.svg, the site's icon sprite, from the vendored SVG fonts (WS-11).

  python3 tools/build_icons.py [--check] [--root PATH]

Glyph outlines come from assets/fonts/fontawesome-webfont.svg (Font Awesome 4.6.3 by
Dave Gandy, font under SIL OFL 1.1, CSS under MIT) and assets/fonts/academicons.svg
(Academicons 1.8 by James Walsh and Katja Bercic, SIL OFL 1.1). A symbol id is the
icon class without its prefix, so fa-github is #github. --check rebuilds in memory
and exits 1 when assets/icons.svg differs. Standard library only.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
FA = "assets/fonts/fontawesome-webfont.svg"
AI = "assets/fonts/academicons.svg"
ICONS = (  # (symbol id, font file, code point as in the vendored CSS)
    ("arxiv", AI, "e974"),
    ("orcid", AI, "e9d9"),
    ("ads", AI, "e9cb"),
    ("github", FA, "f09b"),
    ("linkedin-square", FA, "f08c"),
    ("soundcloud", FA, "f1be"),
    ("envelope-o", FA, "f003"),
)
HEAD = """<svg xmlns="http://www.w3.org/2000/svg">
<!-- Generated by tools/build_icons.py; do not edit by hand.
     Outlines: Font Awesome 4.6.3 by Dave Gandy (font: SIL OFL 1.1, http://scripts.sil.org/OFL)
     and Academicons 1.8 by James Walsh and Katja Bercic (SIL OFL 1.1), from the SVG fonts in assets/fonts/.
     Use: <svg class="icon" aria-hidden="true"><use href="/assets/icons.svg#github"></use></svg> -->
"""


def num(x: float) -> str:
    return f"{x:g}"


def glyph(font_text: str, code: str):
    """(viewBox, path data) of one glyph; y points up in an SVG font, so the path is flipped."""
    face = re.search(r'<font-face[^>]*units-per-em="([\d.]+)"[^>]*ascent="([\d.]+)"[^>]*descent="(-?[\d.]+)"', font_text)
    default_adv = re.search(r'<font [^>]*horiz-adv-x="([\d.]+)"', font_text)
    g = re.search(rf'<glyph\s+unicode="&#x{code};"([^>]*?)/>', font_text)
    if not (face and default_adv and g):
        raise SystemExit(f"build_icons: glyph U+{code.upper()} or the font header not found")
    d = re.search(r'\sd="([^"]+)"', g.group(1))
    adv = re.search(r'horiz-adv-x="([\d.]+)"', g.group(1))
    if not d:
        raise SystemExit(f"build_icons: glyph U+{code.upper()} has no outline")
    units, ascent, descent = float(face.group(1)), float(face.group(2)), float(face.group(3))
    width = float(adv.group(1) if adv else default_adv.group(1))
    return f"0 {num(-ascent)} {num(width)} {num(ascent - descent)}", d.group(1)


def build(root: pathlib.Path) -> str:
    fonts = {rel: (root / rel).read_text(encoding="utf-8") for rel in (FA, AI)}
    out = [HEAD]
    for name, rel, code in ICONS:
        box, d = glyph(fonts[rel], code)
        out.append(f'<symbol id="{name}" viewBox="{box}"><path transform="scale(1 -1)" d="{d}"/></symbol>\n')
    out.append("</svg>\n")
    return "".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build assets/icons.svg from the vendored SVG fonts.")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--root", type=pathlib.Path, default=ROOT)
    a = ap.parse_args(argv)
    text = build(a.root)
    target = a.root / "assets" / "icons.svg"
    if a.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != text:
            print("DRIFT assets/icons.svg icons")
            return 1
        return 0
    target.write_text(text, encoding="utf-8")
    print(f"build_icons: wrote {target.relative_to(a.root)} ({len(ICONS)} symbols, {len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
